from pathlib import Path
p=Path('index.html')
s=p.read_text(encoding='utf-8')

# Favorite controls/styles before the game grid.
style_anchor='''    .game-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:17px;padding:22px}\n'''
style_new='''    .favorite-toolbar{display:flex;align-items:center;gap:10px;padding:12px 22px 0;flex-wrap:wrap}\n    .favorites-filter{height:36px;display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:0 13px;border:1px solid rgba(255,255,255,.28);border-radius:10px;background:rgba(3,52,146,.84);color:#fff;font-size:13px;font-weight:750;cursor:pointer;box-shadow:0 5px 14px rgba(0,30,100,.20),inset 0 1px 0 rgba(255,255,255,.18);transition:transform .16s ease,background .16s ease,box-shadow .16s ease}\n    .favorites-filter:hover{transform:translateY(-2px);background:#063a92;box-shadow:0 8px 18px rgba(0,20,75,.23)}\n    .favorites-filter.is-active{background:#fff;color:#06419f;border-color:#fff}\n    .favorite-badge{position:absolute;top:8px;right:8px;z-index:3;width:34px;height:34px;border:1px solid rgba(255,255,255,.72);border-radius:50%;background:rgba(7,27,68,.78);color:#fff;display:inline-flex;align-items:center;justify-content:center;font-size:19px;line-height:1;cursor:pointer;box-shadow:0 5px 13px rgba(0,0,0,.23);backdrop-filter:blur(3px);transition:transform .16s ease,background .16s ease,color .16s ease}\n    .favorite-badge:hover{transform:scale(1.08);background:rgba(255,255,255,.95);color:#e2a400}\n    .favorite-badge.is-favorite{background:#fff;color:#e2a400}\n    .favorite-empty{margin:8px 22px 22px;padding:28px 18px;border:1px dashed rgba(255,255,255,.25);border-radius:15px;color:rgba(255,255,255,.78);text-align:center;background:rgba(255,255,255,.06)}\n    .favorite-empty strong{display:block;color:#fff;font-size:16px;margin-bottom:5px}\n    .game-grid.favorites-mode .game-card{order:-1}\n'''
if style_anchor not in s: raise SystemExit('game grid style anchor not found')
s=s.replace(style_anchor,style_new+style_anchor,1)

html_anchor='''    <main class="page-wrap">\n      <div id="loadingCard" class="loading-card">Loading games…</div>\n      <div id="gameGrid" class="game-grid"></div>\n'''
html_new='''    <main class="page-wrap">\n      <div id="favoriteToolbar" class="favorite-toolbar" aria-label="Favorite games controls">\n        <button id="favoritesFilter" class="favorites-filter" type="button" aria-pressed="false"><span aria-hidden="true">★</span><span>Favorites</span><span id="favoriteCount">0</span></button>\n      </div>\n      <div id="favoriteEmpty" class="favorite-empty" hidden><strong>No favorites yet</strong><span>Press the ★ on any game to save it here.</span></div>\n      <div id="loadingCard" class="loading-card">Loading games…</div>\n      <div id="gameGrid" class="game-grid"></div>\n'''
if html_anchor not in s: raise SystemExit('main html anchor not found')
s=s.replace(html_anchor,html_new,1)

# Add a robust favorites system before the personalized recommendations block.
marker='''  /* Personalized recommendation carousel */\n'''
fav='''  /* Local favorites */\n  (function(){\n    const grid=document.getElementById('gameGrid');\n    const filter=document.getElementById('favoritesFilter');\n    const countEl=document.getElementById('favoriteCount');\n    const empty=document.getElementById('favoriteEmpty');\n    if(!grid||!filter||!countEl||!empty)return;\n    const KEY='ubg_favorites_v1';\n    const read=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch(_){return[]}};\n    const write=v=>{try{localStorage.setItem(KEY,JSON.stringify(v))}catch(_){}};\n    const cleanTitle=s=>(s||'').replace(/\\s+/g,' ').trim();\n    const norm=s=>cleanTitle(s).toLowerCase();\n    let favoriteMode=false;\n\n    function cardTitle(card){return cleanTitle(card.querySelector('h3')?.textContent||card.querySelector('img')?.alt||'Game')}\n    function favoriteKey(card){const title=cardTitle(card);const src=card.querySelector('img')?.currentSrc||card.querySelector('img')?.src||'';return norm(title)+'|'+src}\n    function addButton(card){\n      if(card.querySelector(':scope > .favorite-badge'))return;\n      const btn=document.createElement('button');btn.type='button';btn.className='favorite-badge';btn.setAttribute('aria-label','Add to favorites');btn.title='Add to favorites';btn.textContent='★';\n      btn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();toggle(card);});\n      card.appendChild(btn);\n    }\n    function isFav(card,set){return set.has(favoriteKey(card))}\n    function apply(){\n      const set=new Set(read());\n      const cards=Array.from(grid.querySelectorAll(':scope > .game-card'));\n      cards.forEach(card=>{\n        addButton(card);\n        const fav=isFav(card,set);\n        const btn=card.querySelector(':scope > .favorite-badge');\n        btn.classList.toggle('is-favorite',fav);btn.setAttribute('aria-label',fav?'Remove from favorites':'Add to favorites');btn.title=fav?'Remove from favorites':'Add to favorites';\n        if(favoriteMode)card.style.display=fav?'':'none';\n        card.dataset.favorite=fav?'true':'false';\n      });\n      const n=cards.filter(c=>isFav(c,set)).length;\n      countEl.textContent=String(n);\n      empty.hidden=!(favoriteMode&&n===0);\n      grid.classList.toggle('favorites-mode',favoriteMode);\n      filter.classList.toggle('is-active',favoriteMode);filter.setAttribute('aria-pressed',String(favoriteMode));\n    }\n    function toggle(card){\n      const current=read();const key=favoriteKey(card);const i=current.indexOf(key);\n      if(i>=0)current.splice(i,1);else current.unshift(key);\n      write(current.slice(0,300));apply();\n    }\n    filter.addEventListener('click',()=>{\n      favoriteMode=!favoriteMode;\n      apply();\n    });\n    new MutationObserver(()=>apply()).observe(grid,{childList:true});\n    apply();\n  })();\n\n'''
if marker not in s: raise SystemExit('recommendations marker not found')
s=s.replace(marker,fav+marker,1)

# Validation marker: the favorites system is intentionally local to each browser.
p.write_text(s,encoding='utf-8')
