from pathlib import Path
import re

FILES=[Path('index.html'),Path('legacy-index.html')]

STYLE='''<style id="ubg43-runtime-stability-style">\n#status{display:none!important}\n.hero-copy p,.hero-copy .hero-stat{display:none!important}\n#v3Trending,#v3New{display:none!important}\nbody.ubg43-search-active #v3Trending,body.ubg43-search-active #v3New{display:block!important}\n</style>'''
BAD_OBSERVER='new MutationObserver(()=>normalize()).observe(document.body,{childList:true,subtree:true});'


def ensure_core_markup(text):
    # The earlier layout cleanup could accidentally remove the gameGrid wrapper. Rebuild it
    # around the existing static cards so the original loader/runtime and V3 runtime have a stable root.
    if not re.search(r'id=["\']gameGrid["\']', text, re.I):
        main=re.search(r'(<main\b[^>]*>)(.*?)(</main\s*>)', text, re.I|re.S)
        if main:
            body=main.group(2)
            cards=re.findall(r'<div\s+class=["\']game-card["\'][^>]*>.*?</div>\s*', body, re.I|re.S)
            if cards:
                body_wo=re.sub(r'<div\s+class=["\']game-card["\'][^>]*>.*?</div>\s*','',body,count=len(cards),flags=re.I|re.S)
                # Keep the existing empty-state node outside the grid.
                grid='\n<div id="gameGrid" class="game-grid">\n'+''.join(cards)+'</div>\n'
                text=text[:main.start(2)]+grid+body_wo+text[main.end(2):]
    # The legacy base runtime expects these containers even though the visible featured rails
    # are now generated by the V3 runtime. Hidden compatibility containers prevent null errors.
    if not re.search(r'id=["\']trendingStrip["\']', text, re.I):
        marker=re.search(r'<div\s+id=["\']gameGrid["\'][^>]*>',text,re.I)
        if marker:text=text[:marker.start()]+'<div id="trendingStrip" hidden></div><div id="newStrip" hidden></div>\n'+text[marker.start():]
    # Remove previously-added canceled site-protection runtime/CSS from generated pages.
    text=re.sub(r'\s*<style id="ubg43-site-protection-style">.*?</style>\s*','\n',text,count=1,flags=re.S)
    text=re.sub(r'\s*<script id="ubg43-site-protection-runtime">.*?</script>\s*','\n',text,count=1,flags=re.S)
    return text


def patch(text):
    text=text.replace(BAD_OBSERVER,'')
    text=re.sub(r'new MutationObserver\(\(\)=>normalize\(\)\)\.observe\(document\.body,\{childList:true,subtree:true\}\);','',text)
    text=text.replace('Building your game library…','').replace('Building your game library...','')
    text=text.replace('1000+ games, quick search, automatic categories, fresh releases and personalized picks — all in one place.','')
    text=text.replace('1000+ games • new games every day • personalized recommendations','')
    text=ensure_core_markup(text)
    text=re.sub(r'\s*<style id="ubg43-runtime-stability-style">.*?</style>\s*','\n',text,count=1,flags=re.S)
    pos=text.lower().rfind('</head>')
    if pos!=-1:text=text[:pos]+STYLE+'\n'+text[pos:]
    return text

for path in FILES:
    if not path.exists():
        continue
    text=patch(path.read_text(encoding='utf-8'))
    path.write_text(text,encoding='utf-8')
    print('RUNTIME STABILITY FIX:',path,'gameGrid=',bool(re.search(r'id=["\']gameGrid["\']',text,re.I)))
