name: Add categories sidebar

on:
  push:
    paths:
      - '.github/category-trigger'

permissions:
  contents: write

jobs:
  categories:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Apply categories sidebar
        run: python3 .github/category-sidebar.py
      - name: Commit categories update
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add index.html
          git commit -m 'Add automatic game categories sidebar' || exit 0
          git push
